# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./build.sh

  lint:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install golint
      - run: golint -set_exit_status ./...

  vet:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: go vet ./...

  unit_tests:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: go test -v -cover ./reach/...

  acceptance_tests:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -sS https://releases.hashicorp.com/terraform/0.12.15/terraform_0.12.15_linux_amd64.zip -o ./terraform.zip && unzip terraform.zip && sudo mv terraform /usr/local/bin/ && which terraform
      - run: go test -cover ./reach/analyzer -test.v -acceptance -log-tf -timeout 60m

workflows:
  version: 2
  push:
    jobs:
      - build
      - lint
      - vet
      - unit_tests
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - acceptance_tests
