# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: CGO_ENABLED=0 go build -a -o "./build/reach"

  unit_tests:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: go test -cover ./reach

  acceptance_tests:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: go test -cover ./... -acceptance -log-tf -test.v

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "36 * * * *"
          filters:
            branches:
              only:
                - same-subnet-int-tests # TODO: Replace with master
    jobs:
      - acceptance_tests
